# Generated by Django 4.0.1 on 2022-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('question', models.CharField(max_length=2048)),
                ('tests', models.CharField(max_length=2048)),
            ],
        ),
    ]
