# Generated by Django 4.0.1 on 2022-02-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('P', 'Project'), ('L', 'Leet Code')], default='L', max_length=1),
        ),
    ]
