# Generated by Django 4.0.1 on 2022-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tests',
            field=models.TextField(),
        ),
    ]
