# Generated by Django 4.0.2 on 2022-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_question_alter_challenge_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='tests',
            field=models.TextField(blank=True),
        ),
    ]
