# Generated by Django 4.0.2 on 2022-03-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_name_alter_group_password_alter_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ist_id',
        ),
    ]
