# Generated by Django 4.0.1 on 2022-02-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('R', 'Running'), ('F', 'Finished'), ('T', 'Timed out'), ('E', 'Exception'), ('N', 'None')], default='C', max_length=1),
        ),
    ]
