# Generated by Django 4.0.1 on 2022-02-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
