# Generated by Django 4.0.2 on 2022-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.TextField(),
        ),
    ]
