# Generated by Django 4.0.2 on 2022-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='original_file_name',
            field=models.TextField(default='_no_name'),
        ),
    ]
